name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure Project
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build Project
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AI-Level-Editor
          path: build/
